name: adorn
description: This is a package developed by Asfaque Ahmed to make the development process easy.
version: 0.0.1


environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  recase:
  dio:
  shared_preferences:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
